org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Work around Gradle 9 default PREFER_SETTINGS conflicting with pluginManagement repositories
org.gradle.configuration-cache.parallel=false
rive.ndk.version=28.2.13676358
android.builder.sdkDownload=false
android.ndk.suppressMinSdkVersionError=21
